language: php

dist: xenial

services:
  - mysql
  - postgresql

env:
  global:
    - COMPOSER_ROOT_VERSION=5.x-dev
    - TRAVIS_NODE_VERSION="10"

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1
      env: DB=PGSQL PHPUNIT_TEST=1 NPM_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.3
      env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:^4
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:^2; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs code/ tests/; fi
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml -vvv; fi
  - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
  - if [[ $NPM_TEST ]]; then git diff -w --no-color --relative=client; fi
  - if [[ $NPM_TEST ]]; then yarn run lint; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
