language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=5.0.x-dev

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL RECIPE_VERSION=1.0.x-dev PHPCS_TEST=1 PHPUNIT_TEST=1
    - php: 7.0
      env: DB=MYSQL RECIPE_VERSION=1.1.x-dev PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=1.2.x-dev PHPUNIT_COVERAGE_TEST=1
    - php: 7.2
      env: DB=MYSQL RECIPE_VERSION=1.x-dev PHPUNIT_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml -vvv; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs code/ tests/; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
