# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

matrix:
  include:
    - php: 5.3
      env: DB=MYSQL CORE_RELEASE=3.1
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.1 SECUREASSETS=1
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.3

before_script:
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - "if [ \"$SECUREASSETS\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
  - "if [ \"$SECUREASSETS\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/secureassets; fi"
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit --coverage-clover coverage.clover userforms/tests
  - wget https://scrutinizer-ci.com/ocular.phar
  - git remote rm origin
  - git remote add origin git@github.com:silverstripe/silverstripe-userforms.git
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
